services:
  tomcat:
    container_name: tomcat
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    environment:
      CATALINA_HOME: /app/tomcat
      CATALINA_BASE: /app/tomcat
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - ${EXTERNAL_TOMCAT_PORT}:8080
    depends_on:
      database:
        condition: "service_healthy"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  database:
    container_name: db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - ${EXTERNAL_DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    container_name: frontend
    build:
      context: currency-exchange-frontend/
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      database:
        condition: "service_healthy"
      tomcat:
        condition: "service_healthy"


volumes:
  pgdata: